replicaCount:
  v10: 1
  v11: 1

image:
  v10:
    repository: quay.io/redhattraining/versioned-hello
    pullPolicy: IfNotPresent
    tag: v1.0
  v11:
    repository: quay.io/redhattraining/versioned-hello
    pullPolicy: IfNotPresent
    tag: v1.1

# Canary Deployment values:
# none: v10 -> 100% v11 -> 0%
# first: v10 -> 90% v11 -> 10%
# half: v10 -> 50% v11 -> 50%
# second: v10-> 10% v11 90%
# full: v10-> 0% v11: 100%
canary: full
